# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeExcercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeExcercise
	pod 'DGElasticPullToRefresh'
	pod 'SnapKit', '~> 4.0.0'
	pod 'Alamofire', '~> 4.5'
	pod 'AlamofireImage', '~> 3.3'

  target 'CodeExcerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodeExcerciseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
